### ISSUE TITLE
Good App. However, some videos do not work.

### ISSUE THREAD

**Issue by chaocharleswang** [tastelessjolt/youtube-dl-android#4] opened 2018-08-10 14:17 UTC
Please check the following video:

https://www.youtube.com/watch?v=5_yKSr8xf1U

Thanks!

**Comment by tastelessjolt** [comment] 2018-08-10 19:20
## [Edit]
It is actually related to `player-age-gate-content`. This is not yet handled in the app. I have to go through `youtube-dl` to see how it is handled.  

------
I think the problem is related to the default quality it selects. This app currently automatically downloads 720p videos. 

I'll look into this video. Thanks for reporting.

**Comment by chaocharleswang** [comment] 2018-08-11 03:25
Wait for your solutions 👍  Thanks!

**Comment by TooLazyy** [comment] 2018-09-28 11:20
Same problem here. 
@tastelessjolt Python youtube-dl has updated recently.

**Comment by tastelessjolt** [comment] 2019-06-07 14:02
I just tried it again, now it's working, so I'm closing this.

**Closed as completed by tastelessjolt** 2019-06-07 14:02 UTC
